---
driver:
  name: ec2
  aws_ssh_key_id: research
  security_group_ids: ["sg-3215495a"]
  region: eu-west-2
  availability_zone: eu-west-2a
  subnet_id: subnet-8db4a2f6
  instance_type: t2.small
  associate_public_ip: true
  interface: dns
  tags: {"Name": "test-kitchen"}

platforms:
  - name: centos-7
    driver:
      image_id: ami-031b0f67
    transport:
      username: centos

transport:
  ssh_key: /opt/learn/terraform/research.pem
  username: centos

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  attributes: {
  }
  data_bags_path: /opt/learn/terraform/chef-repo/data_bags
  environments_path: /opt/learn/terraform/chef-repo/environments
  roles_path: /opt/learn/terraform/chef-repo/roles

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[dependencies::default]
      - recipe[bbnetes::db]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: